from datetime import datetime
datenow1 =datetime.now().date()
print("Fecha:",datenow1)
print("Año fecha1:",datenow1.year)
print("Mes fecha1:",datenow1.month)
print("Dia fecha1:",datenow1.day)

datenow2=datetime.now()
print("Fecha2:,",datenow2)
print("Año fecha2:",datenow2.year)
print("Mes fecha2:",datenow2.month)
print("Dia fecha2:",datenow2.day)
print("hora fecha2:",datenow2.hour)
print("minuto fecha2:",datenow2.minute)
print("segundos fecha2:",datenow2.second)
print("microsegundo fecha2:",datenow2.microsecond)

datenow3=datetime.now()
print("Fecha3:,",datenow3)
print("Año fecha3:",datenow3.year)
print("Mes fecha3:",datenow3.month)
print("Dia fecha3:",datenow3.day)
print("hora fecha3:",datenow3.hour)
print("minuto fecha3:",datenow3.minute)
print("segundos fecha2:",datenow2.second)
print("microsegundo fecha3:",datenow3.microsecond)